services:
  yoctocontainer:
    environment:
      - DISPLAY
      - WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR

    volumes:
      - ${XDG_RUNTIME_DIR}/pipewire-0:/tmp/pipewire-0
      - ${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:/tmp/${WAYLAND_DISPLAY}
      - /tmp/.X11-unix/:/tmp/.X11-unix/
      - /tmp/.docker.xauth:/tmp/.docker.xauth
